# Generated by Django 5.1.6 on 2025-12-19 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Inventory POS', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate in percentage', max_digits=5)),
                ('currency_symbol', models.CharField(default='₱', max_length=5)),
                ('receipt_footer', models.TextField(blank=True, help_text='Text to appear at bottom of receipts')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#6B7280', help_text='Hex color code', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, help_text='Brief description about yourself', max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('theme_preference', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', help_text='Choose your preferred theme', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
