# Generated by Django 5.1.6 on 2026-01-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
    ]
