# Generated by Django 5.1.6 on 2026-01-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product',)},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
