# Generated by Django 5.1.6 on 2026-01-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_cart_unique_together_remove_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cashier',
        ),
    ]
